import SwiftUI

// Generated by Supernova - do not modify manually
public struct AppMeasures {

    // Space

    // Spacing

    // spacing
    public static let spaceSpacingspacingSp0 = 0 
    public static let spaceSpacingspacingSp1 = 2 
    public static let spaceSpacingspacingSp2 = 4 
    public static let spaceSpacingspacingSp3 = 8 
    public static let spaceSpacingspacingSp4 = 10 
    public static let spaceSpacingspacingSp5 = 16 
    public static let spaceSpacingspacingSp6 = 24 
    public static let spaceSpacingspacingSp7 = 32 
    public static let spaceSpacingspacingSp8 = 40 
    public static let spaceSpacingspacingSp9 = 48 
    public static let spaceSpacingspacingSp10 = 56 
    public static let spaceSpacingspacingSp11 = 64 
    public static let spaceSpacingspacingSp12 = 72 
    public static let spaceSpacingspacingSp13 = 80 
    public static let spaceSpacingspacingSp14 = 20 
    public static let spaceSpacingspacingSp15 = 12 

    // Mobile

    /// Very Small Spacing , Used for Tiny Gaps
    public static let spaceSpacingspacingMobile2Xs = 2 
    public static let spaceSpacingspacingMobileXs = 8 
    public static let spaceSpacingspacingMobileSm = 10 

    /// regualr buttons
    public static let spaceSpacingspacingMobileMd = 12 
    public static let spaceSpacingspacingMobileLg = 16 
    public static let spaceSpacingspacingMobileXl = 20 
    public static let spaceSpacingspacingMobile2Xl = 24 
    public static let spaceSpacingspacingMobile3Xl = 32 

    // Desktop

    /// Very Small Spacing , Used for Tiny Gaps
    public static let spaceSpacingspacingDesktop2Xs = 4 
    public static let spaceSpacingspacingDesktopXs = 8 
    public static let spaceSpacingspacingDesktopSm = 16 
    public static let spaceSpacingspacingDesktopMd = 20 
    public static let spaceSpacingspacingDesktopLg = 24 
    public static let spaceSpacingspacingDesktopXl = 32 
    public static let spaceSpacingspacingDesktop2Xl = 40 
    public static let spaceSpacingspacingDesktop3Xl = 48 

    // Font Size

    // Font Size

    // fontSize
    public static let fontSizeFontSizefontSize0 = 14 
    public static let fontSizeFontSizefontSize1 = 16 
    public static let fontSizeFontSizefontSize2 = 18 
    public static let fontSizeFontSizefontSize3 = 20 
    public static let fontSizeFontSizefontSize4 = 24 
    public static let fontSizeFontSizefontSize5 = 28 
    public static let fontSizeFontSizefontSize6 = 32 
    public static let fontSizeFontSizefontSize7 = 40 
    public static let fontSizeFontSizefontSize8 = 56 
    public static let fontSizeFontSizefontSize9 = 64 

    // Line Height

    // Line Height

    // lineHeights
    public static let lineHeightLineHeightlineHeights0 = 18 
    public static let lineHeightLineHeightlineHeights1 = 26 
    public static let lineHeightLineHeightlineHeights2 = 20 
    public static let lineHeightLineHeightlineHeights3 = 72 
    public static let lineHeightLineHeightlineHeights4 = 64 
    public static let lineHeightLineHeightlineHeights5 = 48 
    public static let lineHeightLineHeightlineHeights6 = 32 
    public static let lineHeightLineHeightlineHeights7 = 28 
    public static let lineHeightLineHeightlineHeights8 = 40 
    public static let lineHeightLineHeightlineHeights9 = 36 

    // Border Radius

    // Border Radius

    // borderRadius
    public static let borderRadiusBorderRadiusborderRadiusBr0 = 0 
    public static let borderRadiusBorderRadiusborderRadiusBr1 = 4 
    public static let borderRadiusBorderRadiusborderRadiusBr2 = 6 
    public static let borderRadiusBorderRadiusborderRadiusBr3 = 8 
    public static let borderRadiusBorderRadiusborderRadiusBr4 = 100 

    // Border
    public static let borderRadiusBorderRadiusBorderDefault = 6 
}