import SwiftUI

// Generated by Supernova - do not modify manually
public extension View {

    // border

    func borderBorderSecondryBtnBorder() -> some View {
        return self.border(Color(.sRGB, red: 13/255, green: 13/255, blue: 13/255, opacity: 1), width: 2) 
    }
}