import SwiftUI

// Generated by Supernova - do not modify manually
public extension Gradient {
    
    static let Token = Gradient.TokenGradient()
    
    struct TokenGradient {

        // color

        // Gradient

        public let colorGradientGr1 = LinearGradient(
            gradient: Gradient(stops: [
                Gradient.Stop(color: Color(.sRGB, red: 130/255, green: 0/255, blue: 0/255, opacity: 1), location: 0),
                Gradient.Stop(color: Color(.sRGB, red: 230/255, green: 0/255, blue: 0/255, opacity: 1), location: 1),
            ]),
            startPoint: UnitPoint(x: 0.1464, y: 0.8536),
            endPoint: UnitPoint(x: 0.8536, y: 0.1464) 
        )

        public let colorGradientGr2 = LinearGradient(
            gradient: Gradient(stops: [
                Gradient.Stop(color: Color(.sRGB, red: 34/255, green: 34/255, blue: 34/255, opacity: 1), location: 0),
                Gradient.Stop(color: Color(.sRGB, red: 37/255, green: 40/255, blue: 43/255, opacity: 1), location: 1),
            ]),
            startPoint: UnitPoint(x: 0.1464, y: 0.8536),
            endPoint: UnitPoint(x: 0.8536, y: 0.1464) 
        )

        public let colorGradientGr3 = LinearGradient(
            gradient: Gradient(stops: [
                Gradient.Stop(color: Color(.sRGB, red: 244/255, green: 244/255, blue: 244/255, opacity: 1), location: 0),
                Gradient.Stop(color: Color(.sRGB, red: 250/255, green: 250/255, blue: 250/255, opacity: 1), location: 1),
            ]),
            startPoint: UnitPoint(x: 0.1464, y: 0.8536),
            endPoint: UnitPoint(x: 0.8536, y: 0.1464) 
        )
    }
}