import SwiftUI

// Generated by Supernova - do not modify manually
public extension View {

    func shadowElevation() -> some View {
        return self.shadow(color: Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 0.16), radius: 8, x: 0, y: 2) 
    }
}