import SwiftUI

// Generated by Supernova - do not modify manually
public extension Text {

    // typography

    // Mobile

    // Paragraph

    // Footnote

    func textStyleTypographyMobileParagraphFootnoteLight() -> some View {
        return self
            .font(Font.custom("Vodafone Lt-Regular", size: 14))
    }

    func textStyleTypographyMobileParagraphFootnoteRegular() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Regular", size: 14))
    }

    func textStyleTypographyMobileParagraphFootnoteBold() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Bold", size: 14))
    }

    func textStyleTypographyMobileParagraphFootnoteExtrabold() -> some View {
        return self
            .font(Font.custom("Vodafone ExB-Regular", size: 14))
    }

    // Footnote-underline

    func textStyleTypographyMobileParagraphFootnoteUnderlineLight() -> some View {
        return self
            .font(Font.custom("Vodafone Lt-Regular", size: 14))
            .underline() 
    }

    func textStyleTypographyMobileParagraphFootnoteUnderlineRegular() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Regular", size: 14))
            .underline() 
    }

    func textStyleTypographyMobileParagraphFootnoteUnderlineExtrabold() -> some View {
        return self
            .font(Font.custom("Vodafone ExB-Regular", size: 14))
            .underline() 
    }

    func textStyleTypographyMobileParagraphFootnoteUnderlineBold() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Bold", size: 14))
            .underline() 
    }

    // Body

    func textStyleTypographyMobileParagraphBodyLight() -> some View {
        return self
            .font(Font.custom("Vodafone Lt-Regular", size: 16))
    }

    func textStyleTypographyMobileParagraphBodyRegular() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Regular", size: 16))
    }

    func textStyleTypographyMobileParagraphBodyBold() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Bold", size: 16))
    }

    func textStyleTypographyMobileParagraphBodyExtrabold() -> some View {
        return self
            .font(Font.custom("Vodafone ExB-Regular", size: 16))
    }

    // Body-underline

    func textStyleTypographyMobileParagraphBodyUnderlineLight() -> some View {
        return self
            .font(Font.custom("Vodafone Lt-Regular", size: 16))
            .underline() 
    }

    func textStyleTypographyMobileParagraphBodyUnderlineRegular() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Regular", size: 16))
            .underline() 
    }

    func textStyleTypographyMobileParagraphBodyUnderlineBold() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Bold", size: 16))
            .underline() 
    }

    func textStyleTypographyMobileParagraphBodyUnderlineExtrabold() -> some View {
        return self
            .font(Font.custom("Vodafone ExB-Regular", size: 16))
            .underline() 
    }

    // Headings

    // H5

    func textStyleTypographyMobileHeadingsH5Light() -> some View {
        return self
            .font(Font.custom("Vodafone Lt-Regular", size: 18))
    }

    func textStyleTypographyMobileHeadingsH5Regular() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Regular", size: 18))
    }

    func textStyleTypographyMobileHeadingsH5Bold() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Bold", size: 18))
    }

    func textStyleTypographyMobileHeadingsH5Extrabold() -> some View {
        return self
            .font(Font.custom("Vodafone ExB-Regular", size: 18))
    }

    // H5-underline

    func textStyleTypographyMobileHeadingsH5UnderlineLight() -> some View {
        return self
            .font(Font.custom("Vodafone Lt-Regular", size: 18))
            .underline() 
    }

    func textStyleTypographyMobileHeadingsH5UnderlineRegular() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Regular", size: 18))
            .underline() 
    }

    func textStyleTypographyMobileHeadingsH5UnderlineBold() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Bold", size: 18))
            .underline() 
    }

    func textStyleTypographyMobileHeadingsH5UnderlineExtrabold() -> some View {
        return self
            .font(Font.custom("Vodafone ExB-Regular", size: 18))
            .underline() 
    }

    // H4

    func textStyleTypographyMobileHeadingsH4Light() -> some View {
        return self
            .font(Font.custom("Vodafone Lt-Regular", size: 20))
    }

    func textStyleTypographyMobileHeadingsH4Regular() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Regular", size: 20))
    }

    func textStyleTypographyMobileHeadingsH4Bold() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Bold", size: 20))
    }

    func textStyleTypographyMobileHeadingsH4Extrabold() -> some View {
        return self
            .font(Font.custom("Vodafone ExB-Regular", size: 20))
    }

    // H4-underline

    func textStyleTypographyMobileHeadingsH4UnderlineLight() -> some View {
        return self
            .font(Font.custom("Vodafone Lt-Regular", size: 20))
            .underline() 
    }

    func textStyleTypographyMobileHeadingsH4UnderlineRegular() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Regular", size: 20))
            .underline() 
    }

    func textStyleTypographyMobileHeadingsH4UnderlineBold() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Bold", size: 20))
            .underline() 
    }

    func textStyleTypographyMobileHeadingsH4UnderlineExtrabold() -> some View {
        return self
            .font(Font.custom("Vodafone ExB-Regular", size: 20))
            .underline() 
    }

    // H3

    func textStyleTypographyMobileHeadingsH3Light() -> some View {
        return self
            .font(Font.custom("Vodafone Lt-Regular", size: 24))
    }

    func textStyleTypographyMobileHeadingsH3Regular() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Regular", size: 24))
    }

    func textStyleTypographyMobileHeadingsH3Bold() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Bold", size: 24))
    }

    func textStyleTypographyMobileHeadingsH3Extrabold() -> some View {
        return self
            .font(Font.custom("Vodafone ExB-Regular", size: 24))
    }

    // H2

    func textStyleTypographyMobileHeadingsH2Light() -> some View {
        return self
            .font(Font.custom("Vodafone Lt-Regular", size: 28))
    }

    func textStyleTypographyMobileHeadingsH2Regular() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Regular", size: 28))
    }

    func textStyleTypographyMobileHeadingsH2Bold() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Bold", size: 28))
    }

    func textStyleTypographyMobileHeadingsH2Extrabold() -> some View {
        return self
            .font(Font.custom("Vodafone ExB-Regular", size: 28))
    }

    // H1

    func textStyleTypographyMobileHeadingsH1Light() -> some View {
        return self
            .font(Font.custom("Vodafone Lt-Regular", size: 32))
    }

    func textStyleTypographyMobileHeadingsH1Regular() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Regular", size: 32))
    }

    func textStyleTypographyMobileHeadingsH1Extrabold() -> some View {
        return self
            .font(Font.custom("Vodafone ExB-Regular", size: 32))
    }

    func textStyleTypographyMobileHeadingsH1Bold() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Bold", size: 32))
    }

    // Desktop

    // Paragraph

    // Footnote

    func textStyleTypographyDesktopParagraphFootnoteLight() -> some View {
        return self
            .font(Font.custom("Vodafone Lt-Regular", size: 14))
    }

    func textStyleTypographyDesktopParagraphFootnoteRegular() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Regular", size: 14))
    }

    func textStyleTypographyDesktopParagraphFootnoteBold() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Bold", size: 14))
    }

    func textStyleTypographyDesktopParagraphFootnoteExtrabold() -> some View {
        return self
            .font(Font.custom("Vodafone ExB-Regular", size: 14))
    }

    // Footnote-underline

    func textStyleTypographyDesktopParagraphFootnoteUnderlineLight() -> some View {
        return self
            .font(Font.custom("Vodafone Lt-Regular", size: 14))
            .underline() 
    }

    func textStyleTypographyDesktopParagraphFootnoteUnderlineRegular() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Regular", size: 14))
            .underline() 
    }

    func textStyleTypographyDesktopParagraphFootnoteUnderlineExtrabold() -> some View {
        return self
            .font(Font.custom("Vodafone ExB-Regular", size: 14))
            .underline() 
    }

    func textStyleTypographyDesktopParagraphFootnoteUnderlineBold() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Bold", size: 14))
            .underline() 
    }

    // Body

    func textStyleTypographyDesktopParagraphBodyLight() -> some View {
        return self
            .font(Font.custom("Vodafone Lt-Regular", size: 18))
    }

    func textStyleTypographyDesktopParagraphBodyRegular() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Regular", size: 18))
    }

    func textStyleTypographyDesktopParagraphBodyBold() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Bold", size: 18))
    }

    func textStyleTypographyDesktopParagraphBodyExtrabold() -> some View {
        return self
            .font(Font.custom("Vodafone ExB-Regular", size: 18))
    }

    // Body-underline

    func textStyleTypographyDesktopParagraphBodyUnderlineLight() -> some View {
        return self
            .font(Font.custom("Vodafone Lt-Regular", size: 18))
            .underline() 
    }

    func textStyleTypographyDesktopParagraphBodyUnderlineRegular() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Regular", size: 18))
            .underline() 
    }

    func textStyleTypographyDesktopParagraphBodyUnderlineBold() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Bold", size: 18))
            .underline() 
    }

    func textStyleTypographyDesktopParagraphBodyUnderlineExtrabold() -> some View {
        return self
            .font(Font.custom("Vodafone ExB-Regular", size: 18))
            .underline() 
    }

    // Headings

    // H5

    func textStyleTypographyDesktopHeadingsH5Light() -> some View {
        return self
            .font(Font.custom("Vodafone Lt-Regular", size: 20))
    }

    func textStyleTypographyDesktopHeadingsH5Regular() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Regular", size: 20))
    }

    func textStyleTypographyDesktopHeadingsH5Bold() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Bold", size: 20))
    }

    func textStyleTypographyDesktopHeadingsH5Extrabold() -> some View {
        return self
            .font(Font.custom("Vodafone ExB-Regular", size: 20))
    }

    // H5-underline

    func textStyleTypographyDesktopHeadingsH5UnderlineLight() -> some View {
        return self
            .font(Font.custom("Vodafone Lt-Regular", size: 20))
            .underline() 
    }

    func textStyleTypographyDesktopHeadingsH5UnderlineRegular() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Regular", size: 20))
            .underline() 
    }

    func textStyleTypographyDesktopHeadingsH5UnderlineBold() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Bold", size: 20))
            .underline() 
    }

    func textStyleTypographyDesktopHeadingsH5UnderlineExtrabold() -> some View {
        return self
            .font(Font.custom("Vodafone ExB-Regular", size: 18))
            .underline() 
    }

    // H4

    func textStyleTypographyDesktopHeadingsH4Light() -> some View {
        return self
            .font(Font.custom("Vodafone Lt-Regular", size: 28))
    }

    func textStyleTypographyDesktopHeadingsH4Regular() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Regular", size: 28))
    }

    func textStyleTypographyDesktopHeadingsH4Bold() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Bold", size: 28))
    }

    func textStyleTypographyDesktopHeadingsH4Extrabold() -> some View {
        return self
            .font(Font.custom("Vodafone ExB-Regular", size: 28))
    }

    // H4-underline

    func textStyleTypographyDesktopHeadingsH4UnderlineLight() -> some View {
        return self
            .font(Font.custom("Vodafone Lt-Regular", size: 28))
            .underline() 
    }

    func textStyleTypographyDesktopHeadingsH4UnderlineRegular() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Regular", size: 28))
            .underline() 
    }

    func textStyleTypographyDesktopHeadingsH4UnderlineBold() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Bold", size: 28))
            .underline() 
    }

    func textStyleTypographyDesktopHeadingsH4UnderlineExtrabold() -> some View {
        return self
            .font(Font.custom("Vodafone ExB-Regular", size: 28))
            .underline() 
    }

    // H3

    func textStyleTypographyDesktopHeadingsH3Light() -> some View {
        return self
            .font(Font.custom("Vodafone Lt-Regular", size: 40))
    }

    func textStyleTypographyDesktopHeadingsH3Regular() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Regular", size: 40))
    }

    func textStyleTypographyDesktopHeadingsH3Bold() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Bold", size: 40))
    }

    func textStyleTypographyDesktopHeadingsH3Extrabold() -> some View {
        return self
            .font(Font.custom("Vodafone ExB-Regular", size: 40))
    }

    // H2

    func textStyleTypographyDesktopHeadingsH2Light() -> some View {
        return self
            .font(Font.custom("Vodafone Lt-Regular", size: 56))
    }

    func textStyleTypographyDesktopHeadingsH2Regular() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Regular", size: 56))
    }

    func textStyleTypographyDesktopHeadingsH2Bold() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Bold", size: 56))
    }

    func textStyleTypographyDesktopHeadingsH2Extrabold() -> some View {
        return self
            .font(Font.custom("Vodafone ExB-Regular", size: 56))
    }

    // H1

    func textStyleTypographyDesktopHeadingsH1Light() -> some View {
        return self
            .font(Font.custom("Vodafone Lt-Regular", size: 64))
    }

    func textStyleTypographyDesktopHeadingsH1Regular() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Regular", size: 64))
    }

    func textStyleTypographyDesktopHeadingsH1Bold() -> some View {
        return self
            .font(Font.custom("Vodafone Rg-Bold", size: 64))
    }

    func textStyleTypographyDesktopHeadingsH1Extrabold() -> some View {
        return self
            .font(Font.custom("Vodafone ExB-Regular", size: 64))
    }
}
